[aliases]
vault = "/Obsidian"
projects = "@vault/Projects"
ideas = "@projects/Brain Vomit"
journal = "@vault/Personal/Journal/2026"
studies = "@vault/Studies/University/Year 2/T2"

[hosts]
"@projects/OSS" = ["dav-worker", "Pirell"]
"@projects/GDG" = ["Folia"]

[patterns]
"*/spec"          = "*/Docs/SPEC.md"
"*/code"          = "*/Code"
"*/src"           = "*/Code/src"
"dav-worker/code" = "@dav-worker/Code/dav-worker"
"dav-worker/src"  = "@dav-worker/Code/dav-worker/src"
"journal/all"     = "@vault/Personal/Journal"
