// Augment the global Env with secrets not generated by `wrangler types`.
// Secrets are set via `wrangler secret put` and live only at runtime.
declare global {
  interface Env {
    NEXTCLOUD_HOST: string;
    NEXTCLOUD_USERNAME: string;
    NEXTCLOUD_PASSWORD: string;
  }
}

export {};
